import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import LeftAside from "@/components/LeftAside";
import RightAside from "@/components/RightAside";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <div className="max-w-[1920px] mx-auto bg-[url('/assets/layoutBG.png')] bg-repeat-y py-20">
          <div
            className="max-w-[1320px] mx-auto bg-[#171B1A]"
            style={{
              boxShadow: "0 25px 50px -12px rgba(255, 255, 255, 0.25)", // white shadow
            }}
          >
            <nav className="relative z-20">
              <span className="absolute -top-[80px] -left-[110px] z-10 font-bold text-[90px] text-white opacity-[0.06]">
                Home
              </span>

              <div className="relative z-20">
                <Navbar />
              </div>
            </nav>

            <div className="grid grid-cols-1 md:grid-cols-12 min-h-screen">
              {/* Left Aside - hidden on mobile, appears on md+ */}
              <aside className="hidden md:block md:col-span-1">
                <LeftAside />
              </aside>

              {/* Main - takes full width on mobile, 10/12 on md+ */}
              <main className="col-span-1 md:col-span-10">{children}</main>

              {/* Right Aside - hidden on mobile, appears on md+ */}
              <aside className="hidden md:block md:col-span-1">
                <RightAside />
              </aside>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
